Adding customerAccount field to invoice response closes #71
ewngs/szamlazz.js pull request #72
Opened 2024-09-06 11:17 UTC by laszloerno

2024-09-07 11:09 UTC, ert78gb requested changes
Thx for the PR. Please fix the unit test too.

2024-09-07 11:09 UTC, ert78gb commented on lib/Client.js
> +      customerAccount: httpResponse.headers.szlahu_vevoifiokurl,
```suggestion
      customerAccountUrl: httpResponse.headers.szlahu_vevoifiokurl,
```

I think the `Url` suffix more future proof.

2024-09-07 16:41 UTC, laszloerno commented
hi thanks i hope i fixed it now :)

2024-09-07 16:44 UTC, ert78gb commented
test is failed

2024-09-07 16:51 UTC, laszloerno commented
sorry this is my first time i add something to somebodys code :)

2024-09-07 16:56 UTC, ert78gb approved these changes

2024-09-07 16:58 UTC, ert78gb requested changes
No worries. Take your time.

Please add a test case that validates the new `customerAccountUrl` has the expected proper value

2024-09-07 17:00 UTC, ert78gb commented
you could run the test on your development environment with `npm run` command

2024-09-07 17:05 UTC, ert78gb commented
And please review your commits/PR and the PR should contains only the modification that are relevant. 
Honestly I don't prefer to reformatting, or do other stylish things because it makes complicated to follow the git history.

2024-09-07 18:25 UTC, laszloerno commented
> And please review your commits/PR and the PR should contains only the modification that are relevant. Honestly I don't prefer to reformatting, or do other stylish things because it makes complicated to follow the git history.

yes i saw it and disabled format on save. but too late. :( should i delete this PR and create a new without thoose commits?

2024-09-07 18:27 UTC, ert78gb commented
not need. leave them. just add the missing unit test

2024-09-07 18:32 UTC, laszloerno commented
i will add like this 
```
it('should have `customerAccountUrl` property', async () => {
        const httpResponse = await client.issueInvoice(invoice)
        expect(httpResponse).to.have.property('customerAccountUrl').that.is.oneOf([undefined, 'string']);
      })
```
as this field is filled only if the account has set customer accounts active

2024-09-07 19:05 UTC, ert78gb commented
Sry for I don't show the good answer, but I mentored so many developers and I like if they find the answer.

There are 2 option
- the customer has account and in this case the `szlahu_vevoifiokurl` has been filled with the value.  In this case we need a test that ensure the value of the `customerAccountUrl` is filled with the `szlahu_vevoifiokurl` 

- the customer does not have account in this case the `szlahu_vevoifiokurl` is empty.  Unfortunately the szamlazz.hu documentation is not 100% accurate because it does not contain if the field is empty then the value of `szlahu_vevoifiokurl` is empty string or not provided in the header. I think if the `szlahu_vevoifiokurl` is falsy then the `customerAccountUrl` should be `undefined`

I just now had time to properly check the documentation of szamlazz.hu. The response of `issueInvoice` and `reverseInvoice` are contain the `szlahu_vevoifiokurl`. So please extend both method, write the test and extend the documentation in both cases.

I understand to hard to maintain others code but this is the reality.  Most of the time we read others code, documentations and try to understand.
If you don't wanna spend time on it just let me know and I will finish the PR.

2024-09-07 19:10 UTC, laszloerno commented
> Sry for I don't show the good answer, but I mentored so many developers and I like if they find the answer.
> 
> There are 2 option
> 
> * the customer has account and in this case the `szlahu_vevoifiokurl` has been filled with the value.  In this case we need a test that ensure the value of the `customerAccountUrl` is filled with the `szlahu_vevoifiokurl`
> * the customer does not have account in this case the `szlahu_vevoifiokurl` is empty.  Unfortunately the szamlazz.hu documentation is not 100% accurate because it does not contain if the field is empty then the value of `szlahu_vevoifiokurl` is empty string or not provided in the header. I think if the `szlahu_vevoifiokurl` is falsy then the `customerAccountUrl` should be `undefined`
> 
> I just now had time to properly check the documentation of szamlazz.hu. The response of `issueInvoice` and `reverseInvoice` are contain the `szlahu_vevoifiokurl`. So please extend both method, write the test and extend the documentation in both cases.
> 
> I understand to hard to maintain others code but this is the reality. Most of the time we read others code, documentations and try to understand. If you don't wanna spend time on it just let me know and I will finish the PR.

non it is fine, as a "hobby" ex. developer i want to come back into that :) i appriciate your help! i will extend it now also for the reversal (i overseen it because im not using this)

2024-09-07 19:20 UTC, laszloerno commented
i enhanced also the reverseInvoice. but for this method there were no test cases. I adjusted a little the docu that the response is written for booth cases createinvoice and reverseInvoice. actually it was only for reverse.

2024-09-07 19:23 UTC, ert78gb commented
> but for this method there were no test cases.

please wrote them. I am not the original developer of this package. I just maintain it, but every time when I have to modify it I try to add the missing test.
thx

2024-09-11 15:43 UTC, laszloerno commented
sorry for the delay but had to much work, i added a test case for reversal + i enhanced the createInvoice case at one place where the customerAccountUrl is missing and once where is it there.

2024-09-11 18:51 UTC, ert78gb requested changes

2024-09-11 18:51 UTC, ert78gb commented on tests/client.spec.js
> +        expect(httpResponse).to.have.property('customerAccountUrl').that.is.satisfies((value) => typeof value === 'string' || value === undefined);
```suggestion
        expect(httpResponse.customerAccountUrl).to.be.equals('https://www.szamlazz.hu/szamla/fiok/gd82embu556d2qjagzj3s2ijqeqzds4ckhuf')
```

This test ensure the `customerAccountUrl` has been mapped correctly.

2024-09-11 18:51 UTC, ert78gb commented on tests/client.spec.js
> +        expect(httpResponse).to.have.property('customerAccountUrl').that.is.satisfies((value) => typeof value === 'string' || value === undefined);
```suggestion
        expect(httpResponse.customerAccountUrl).to.be.equals('https://www.szamlazz.hu/szamla/fiok/gd82embu556d2qjagzj3s2ijqeqzds4ckhuf')
```

2024-09-12 07:45 UTC, ert78gb approved these changes

2024-09-12 07:46 UTC, ert78gb commented
@laszloerno Thank you for your contribution

2024-09-12 07:46 UTC, merged